"""empty message

Revision ID: 3191e5718887
Revises: 5e2871aa5a15
Create Date: 2020-02-29 15:34:51.525992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3191e5718887'
down_revision = '5e2871aa5a15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('todo_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'todo_id')
    # ### end Alembic commands ###
